schema = 1
name = "yq"
version = "4.53.3"
description = "Portable command-line YAML, JSON, XML, CSV, TOML, HCL and properties processor"
homepage = "https://github.com/mikefarah/yq"
license = "MIT"
aliases = []
provides = []
conflicts = []

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/mikefarah/yq/releases/download/v4.53.3/yq_windows_amd64.exe"
sha256 = "e279bc506a452eeafcdf364f91a025455e402a8001169083caf01f4b64a544e2"
archive = "raw"
strip_components = 0

[[artifacts.binaries]]
source = "yq_windows_amd64.exe"
name = "yq.exe"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/mikefarah/yq/releases/download/v4.53.3/yq_windows_arm64.exe"
sha256 = "c80ac96ff2a8d77d452d91304e11feef8fb23239900b3d1d88f47c2ec93be970"
archive = "raw"
strip_components = 0

[[artifacts.binaries]]
source = "yq_windows_arm64.exe"
name = "yq.exe"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/mikefarah/yq/releases/download/v4.53.3/yq_linux_amd64"
sha256 = "fa52a4e758c63d38299163fbdd1edfb4c4963247918bf9c1c5d31d84789eded4"
archive = "raw"
strip_components = 0

[[artifacts.binaries]]
source = "yq_linux_amd64"
name = "yq"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/mikefarah/yq/releases/download/v4.53.3/yq_linux_arm64"
sha256 = "578648e463a11c1b6db6010cbf41eafed6bee79466fcffa1bb446672cf7945ea"
archive = "raw"
strip_components = 0

[[artifacts.binaries]]
source = "yq_linux_arm64"
name = "yq"
